### ISSUE TITLE
Applying a Remote Description should allow reuse of transceivers added via addTransceiver

### ISSUE THREAD

**Issue by soareschen** [rtcweb-wg/jsep#759] opened 2017-07-11 05:10 UTC
Currently the paragraph in section 5.9. says:

> If the m= section is sendrecv or recvonly, and there are RtpTransceivers of the same type that were added to the PeerConnection by addTrack and are not associated with any m= section and are not stopped, find the first (according to the canonical order described in Section 5.2.1) such RtpTransceiver.

It should also allow RtpTransceivers added by `addTransceiver` to be reused.

**Comment by taylor-b** [comment] 2017-07-12 00:43
This was actually by design (and is consistent with JSEP). We have all this special matching logic specifically for backwards compatibility with existing apps using `addTrack` (or `addStream`); they're used to being able to call `addTrack` on both sides before doing any offer/answer.

When we tried to extend the matching logic to transceivers added via `addTransceiver`, it opened a can of worms the working group didn't want to get into. So we specifically restricted this logic to transceivers added via `addTrack`, which are not yet "associated" (don't have a MID).

**Comment by soareschen** [comment] 2017-07-12 02:53
I see. How do we distinguish transceivers created via `addTrack` vs `addTransceiver`? In webrtc the transceiver created from addTransceiver also have null `mid`, meaning they are also not "associated"?

**Comment by taylor-b** [comment] 2017-07-12 03:02
There's nothing in the standard that distinguishes them; I guess it's assumed that the implementation has some internal flag it sets (which we could surface to the standard, as an internal slot...)

**Comment by juberti** [comment] 2017-07-28 22:51
Closing per Taylor's by design comment.

**Closed by juberti** 2017-07-28 22:51 UTC
