### ISSUE TITLE
Way to indicate upper bounds on resolution / frame rate to receive 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#30] opened 2014-05-20 15:11 UTC
There needs to be a way for a browser to indicate the upper bound of what it can receive (if it wants too). A mobile device may want to indicate not to send video larger than it's screen. A desktop system may not want to indicate any limit. The w3c API might surface a control surface for this. 

If the browser receives a limit on what the other side can send or receive, it needs to honor that.

**Comment by juberti** [comment] 2015-03-26 05:11
IETF 92: add a=imageattr:X recv that contains the decoder limits, minimaxed with an app-specified receive limit (possibly multiple of these if there are multiple codecs with different limits).

Open question: how does the offerer set receive limits other than decoder limits? This again does suggest that RtpReceiver might need to be created at an earlier stage than ontrack.

**Comment by juberti** [comment] 2015-03-26 05:12
Closing since this is a dupe of #5

**Closed by juberti** 2015-03-26 05:12 UTC
Labels: enhancement
