### ISSUE TITLE
Ensure DTLS role is maintained during SDP renegotiation

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#72] opened 2014-07-14 19:37 UTC
Add text to make it clear that if you are in the passive role, and an actpass offer comes in, you want to keep passive instead of picking active (as would typically be the case).

**Comment by juberti** [comment] 2015-03-26 05:06
Agreement at IETF 92 to use the actual values during reoffers - then nothing gets screwed up. actpass should be tolerated as well for historical reasons, not sure whether that needs to make it into the text.

**Comment by rshpount** [comment] 2016-04-08 23:21
One clarification here: Setup role MUST be currently negotiated role if not accompanied by ICE restart and SHOULD be actpass in case of ICE restart. The reason for this is that answerer is allowed to start a new DTLS association in response to the offer with ICE restart. When answerer starts a new DTLS association, it might be beneficial to change the DTLS setup role. Answerer is not allowed to start new DTLS association if offerer did not initiate an ICE restart since new transport cannot be created for the DTLS association.

**Comment by juberti** [comment] 2016-04-15 16:23
There's no API in WebRTC to restart DTLS. Ergo, we don't need to do actpass for ICE restart.

**Comment by juberti** [comment] 2016-04-15 16:25
We also need to add dtls-association-id to the generated SDP.

**Comment by rshpount** [comment] 2016-04-15 16:30
WebRTC end point is not going to restart DTLS. The remote end point is restarting DTLS. It does not have to be a browser and is free to do anything standard compliant. One of those things is restarting DTLS. When doing so, it is likely to change the setup role. One thing which is currently recommended is to respond with active setup role when establishing new DTLS association in order to decrease the new association setup time.

**Comment by juberti** [comment] 2016-04-18 03:54
I don't understand the problem here. If some non-JSEP endpoint restarts ICE and DTLS, that is fine. But JSEP endpoints don't need to do actpass.

**Comment by rshpount** [comment] 2016-04-18 14:48
The issue is that with DTLS SDP either offerer or the answerer can start a new DTLS association. When ICE is used, answerer is only allowed to start a new DTLS association when remote party initiated an ICE restart, since this is the only way to provide a distinct transport to disambiguate new DTLS association from the old one.

In the scenario I am describing, a JSEP end point sends an offer with ICE restart to some other remote end point. This remote end point can be a WebRTC compatible application, gateway, or anything else compatible with WebRTC. This answering end point can decide to start a new DTLS association, even though offering end point was planning to reuse the existing one. It will set a new DTLS association ID and potentially change fingerprints. To minimize the DTLS association setup time, answering end point should set its DTLS setup role to active. If something else was negotiated before and if the offerer sent its previous role, this will not be possible. If offerer sent the actpass role, then answerer can set the desired role.

This is the lengthy explanation, but the typical way things worked so far, was the offerer would send actpass and answerer will send the active role, unless it establishes a new DTLS association.

**Comment by juberti** [comment] 2016-04-20 05:24
I see your point - basically that when restarting ICE, the offerer should also allow DTLS to also be completely restarted at that time. Is there a clear use case for this?

**Comment by rshpount** [comment] 2016-04-20 14:31
We are generally talking about the use case for answerer initiating a new DTLS association, which was always a part of DTLS-SRTP and related protocols.. The use case is typically when communicating with some sort of communication service (such as conferencing) where a single signaling agent is managing connections to multiple media processing resources. Such signal processing agent might need to move a call from one media processing resource to another on session update, typically to deal with different resource capabilities (for instance move a call to a different media processor when video is requested). When session is moved to a new media processor, new DTLS association would need to be established. Currently this is only possible in response to ICE restart, but I hope, we might find a way to do this in response to any ICE offer in the future. Inability to move the session to a new destination when ICE is used and when offerer did not initiate ICE restart is one of the major shortcoming of ICE. Typical work around is to initiate another session update from the answering side when moving the session to new destination is required but this complicates things immensely. Fixing this is obviously out of scope for this particular issue, but, at the very least, I do not want to break things that do work.

**Comment by cdh4u** [comment] 2016-08-14 13:57
It would probably be good to reference DTLS SDP also for this.

**Comment by ekr** [comment] 2016-09-02 21:45
Duplicate of #230

**Closed by ekr** 2016-09-02 21:45 UTC
Labels: editor-ready
